const assert = (ok: unknown, msg: string) => { if (!ok) throw new Error(msg); };
import { applyPrefix, continueList, lineClass, renderDocument, renderLine } from "./markdown";

assert(lineClass("# Title") === "md-h1", "h1 class");
assert(lineClass("#NoSpace") === "", "hash without space is not a heading");
assert(lineClass("- [x] done") === "md-task md-task-done", "done task before plain task");
assert(lineClass("- [ ] todo") === "md-task", "task before bullet");
assert(lineClass("- item") === "md-bullet", "bullet");
assert(renderLine("# Title").startsWith('<span class="md-mark"># </span>'), "heading marker is hideable");
assert(renderLine("<script>") === "&lt;script&gt;", "escapes html");
assert(renderLine("").includes("br"), "empty line keeps height");
assert(renderLine("# ").includes("br"), "prefix-only line keeps height");
assert(renderLine("a **b** c").includes("md-bold"), "bold");
assert(renderLine("**b**").includes("md-italic") === false, "bold is not re-matched as italic");
assert(renderLine("2 * 3 * 4").includes("md-italic") === false, "no stray italics");
assert(renderLine("[t](u)").includes("md-link"), "link");
assert(renderDocument("a\nb").split("<div").length === 3, "one block per line");
assert(renderDocument("  - x").includes("padding-left:1.5rem"), "indent becomes padding");
assert(continueList("- item") === "- ", "bullet continues");
assert(continueList("  3. item") === "  4. ", "ordinal increments");
assert(continueList("- [x] done") === "- [ ] ", "task resets");
assert(continueList("- ") === "", "empty bullet stops");
assert(continueList("plain") === "", "plain line");
assert(applyPrefix("- old", "## ") === "## old", "prefix replaces prefix");
assert(applyPrefix("plain", "> ") === "> plain", "prefix on plain line");
assert(applyPrefix("# h", "") === "h", "Text command clears prefix");
console.log("markdown ok");
