import type { I18nKey } from "../locales/en";

export type IconGroup = {
  labelKey: I18nKey;
  names: readonly string[];
};

export const lucideIconGroups = [
  {
    labelKey: "page.category.notes",
    names: [
      "FileText",
      "FileCode",
      "Book",
      "BookOpen",
      "NotebookPen",
      "PenLine",
      "PenTool",
      "Highlighter",
      "Quote",
      "Newspaper",
      "Bookmark",
      "Tag",
      "Hash",
      "Paperclip",
      "Archive",
      "Inbox",
      "Folder",
      "FolderOpen",
      "Layers",
      "Search",
    ],
  },
  {
    labelKey: "page.category.work",
    names: [
      "Briefcase",
      "Target",
      "ListTodo",
      "ListChecks",
      "ClipboardList",
      "CircleCheckBig",
      "Calendar",
      "CalendarDays",
      "Clock",
      "AlarmClock",
      "Timer",
      "Bell",
      "Flag",
      "TrendingUp",
      "ChartColumn",
      "ChartPie",
      "Calculator",
      "Building",
      "Users",
      "User",
    ],
  },
  {
    labelKey: "page.category.tech",
    names: [
      "Code",
      "Terminal",
      "GitBranch",
      "Database",
      "Server",
      "Cpu",
      "Bug",
      "Shield",
      "Key",
      "Lock",
      "Settings",
      "Wrench",
      "Hammer",
      "Laptop",
      "Monitor",
      "Smartphone",
      "Printer",
      "Link",
      "Globe",
      "Grid2x2",
    ],
  },
  {
    labelKey: "page.category.media",
    names: [
      "Image",
      "Camera",
      "Film",
      "Music",
      "Headphones",
      "Mic",
      "Radio",
      "Tv",
      "Palette",
      "Brush",
      "Scissors",
      "Shapes",
      "Puzzle",
      "Gamepad2",
      "MessageCircle",
      "Mail",
      "Phone",
      "Languages",
      "Trophy",
      "Medal",
    ],
  },
  {
    labelKey: "page.category.life",
    names: [
      "House",
      "Coffee",
      "Utensils",
      "Pizza",
      "Gift",
      "PartyPopper",
      "Heart",
      "Smile",
      "Dumbbell",
      "HeartPulse",
      "Pill",
      "Stethoscope",
      "Wallet",
      "CreditCard",
      "Banknote",
      "ShoppingCart",
      "Store",
      "Package",
      "Truck",
      "Crown",
    ],
  },
  {
    labelKey: "page.category.nature",
    names: [
      "Leaf",
      "Trees",
      "Mountain",
      "WavesHorizontal",
      "Sun",
      "Moon",
      "Cloud",
      "Droplet",
      "Flame",
      "Zap",
      "Dog",
      "Cat",
      "Compass",
      "Map",
      "MapPin",
      "Anchor",
      "Plane",
      "Car",
      "Bike",
      "TrainFront",
    ],
  },
  {
    labelKey: "page.category.science",
    names: [
      "Lightbulb",
      "Brain",
      "Atom",
      "Dna",
      "Microscope",
      "FlaskConical",
      "GraduationCap",
      "Rocket",
      "Sparkles",
      "Star",
      "Gem",
      "Swords",
      "Activity",
      "Infinity",
    ],
  },
] as const satisfies readonly IconGroup[];

export type LucideIconName = (typeof lucideIconGroups)[number]["names"][number];

export const emojiIconGroups: IconGroup[] = [
  {
    labelKey: "page.category.notes",
    names: [
      "📝",
      "📄",
      "📚",
      "📖",
      "🗒️",
      "📔",
      "🔖",
      "📌",
      "📎",
      "🗂️",
      "📁",
      "🗃️",
    ],
  },
  {
    labelKey: "page.category.work",
    names: [
      "💼",
      "✅",
      "☑️",
      "🎯",
      "📊",
      "📈",
      "🗓️",
      "⏰",
      "⏳",
      "🔔",
      "🚩",
      "🏢",
    ],
  },
  {
    labelKey: "page.category.tech",
    names: [
      "💻",
      "🖥️",
      "⌨️",
      "🐛",
      "🔧",
      "⚙️",
      "🔐",
      "🔑",
      "🗄️",
      "🛰️",
      "🔗",
      "🌐",
    ],
  },
  {
    labelKey: "page.category.media",
    names: [
      "🖼️",
      "📷",
      "🎬",
      "🎵",
      "🎧",
      "🎤",
      "📻",
      "🎨",
      "✂️",
      "🎮",
      "💬",
      "📧",
    ],
  },
  {
    labelKey: "page.category.life",
    names: [
      "🏠",
      "☕",
      "🍕",
      "🍽️",
      "🎁",
      "🎉",
      "❤️",
      "😀",
      "🏋️",
      "💊",
      "💰",
      "🛒",
    ],
  },
  {
    labelKey: "page.category.nature",
    names: [
      "🌿",
      "🌲",
      "⛰️",
      "🌊",
      "☀️",
      "🌙",
      "☁️",
      "💧",
      "🔥",
      "⚡",
      "🐶",
      "🐱",
    ],
  },
  {
    labelKey: "page.category.science",
    names: [
      "💡",
      "🧠",
      "⚛️",
      "🧬",
      "🔬",
      "🧪",
      "🎓",
      "🚀",
      "✨",
      "⭐",
      "💎",
      "♾️",
    ],
  },
];
